version: '3'
services:
  team-java-app:
    image: team-java-app:1.0
    environment:
      - DB_NAME=${DB_NAME}
      - DB_PWD=${DB_PWD}
      - DB_SERVER=${DB_SERVER}
      - DB_USER=${DB_USER}
    ports:
      - 8080:8080
    container_name: team-java-app
    depends_on:
      - mySQL

  mySQL:
    image: mysql:8.2.0
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:5.2.1-apache
    ports:
      - 8085:80
    environment:
      - PMA_HOST=${PMA_HOST}
      - PMA_PORT=${PMA_PORT}

volumes:
  mysql-data:
    driver: local


