version: '3'
services:
  team-java-app:
    image: team-java-app:1.0
    environment:
      - DB_NAME=teambase
      - DB_PWD=teambaseuserPass
      - DB_SERVER=localhost
      - DB_USER=teambaseuser
    ports:
      - 8080:8080
    container_name: team-java-app
    depends_on:
      - mySQL

  mySQL:
    image: mysql:8.2.0
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=dbPass2
      - MYSQL_DATABASE=teambase
      - MYSQL_USER=teambaseuser
      - MYSQL_PASSWORD=teambaseuserPass
    volumes:
      - mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:5.2.1-apache
    ports:
      - 8085:80
    environment:
      - PMA_HOST=mySQL

volumes:
  mysql-data:
    driver: local


